version: '3'
services:
  api:
    image: iyjian/input-server
    restart: always
    ports:
      - 3000:3000
    command: >
      sh -c "
        node dist/main.js
      "
  mongodb:
    restart: unless-stopped
    image: mongo:3.6.5
    volumes:
      - ./mongodata:/data/db
    # ports:
    #   - "27017:27017"
